[build]
  # Ejecuta tu build antes de desplegar
  command = "npm run build"
  # Publica desde la raíz (index.html + dist/)
  publish = "./"

[dev]
  # Puerto del servidor local de Netlify Dev
  port = 8888
  # Carpeta desde la que se sirven los archivos en desarrollo
  publish = "./"

# Configuración opcional de caché para acelerar builds
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
